name: dbt_05

profile: dbt_05

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_05:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
